name: remote_mouse
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1


environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: 0.13.4
  control_pad: 1.1.1+1
  web_socket_channel: 2.1.0
  reflectable: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
